blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path("<int:year>/<int:month>/<int:day>/<slug:post>/",
         views.post_detail, name="post_detail"),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("", views.post_list, name="post_list"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import RedirectView

from blog.sitemaps import PostSitemap

sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps},
         name="django.contrib.sitemaps.views.sitemap"),
    path("", RedirectView.as_view(url="/blog/"))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

from taggit.managers import TaggableManager

from .managers import PublishedManager


class Post(models.Model):
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published")
    )
    
    title = models.CharField(max_length=256)
    slug = models.SlugField(max_length=256)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="draft"
    )
    
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()
    
    class Meta:
        ordering = "-publish",
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse(
            "blog:post_detail", args=(self.publish.year,
                                      self.publish.month,
                                      self.publish.day,
                                      self.slug)
        )


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    name = models.CharField(max_length=64)
    email = models.EmailField()
    body = models.CharField(max_length=512)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = "-created",
        
    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = "name", "email", "body"
    
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields["body"].widget = forms.Textarea()


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=32)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count

from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm


def post_share(request, post_id):
    post: Post = get_object_or_404(Post, id=post_id, status="published")
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} recommends you read {post.title}'
            message = f'Read {post.title} at {post_url}\n\n'\
                      f'{cd["name"]}\'s comments: {cd["comments"]}'
            send_mail(subject, message, "admin@myblog.in", (cd["to"],))
            sent = True
    else:
        form = EmailPostForm()
    return render(request, "blog/post/share.html",
                  {"post": post, "form": form, "sent": sent})


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=(tag,))
    paginator = Paginator(object_list, 15)   # 15 posts per page
    page = request.GET.get("page")
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, "blog/post/list.html",
                  {"posts": posts, "page": page, "tag": tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post, slug=post, status="published",
        publish__year=year, publish__month=month, publish__day=day
    )
    
    comments = post.comments.filter(active=True)
    
    new_comment = None
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment: Comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    
    # Get ids of all the tags in the current post
    post_tag_ids = post.tags.values_list("id", flat=True)
    
    # Filter out published posts which have any of the ids excluding current
    # post
    similar_posts = Post.published.filter(tags__in=post_tag_ids)\
                                  .exclude(id=post.id)
    # Arrange the post latest posts with maximum mathcing tags.
    similar_posts = similar_posts.annotate(same_tags=Count("tags"))\
                                 .order_by("-same_tags", "-publish")[:5]
    
    return render(request, "blog/post/detail.html",
                  {"post": post, "comments": comments,
                   "new_comment": new_comment, "comment_form": comment_form,
                   "similar_posts": similar_posts})

blog/templates/blog/post/detail.html
{% extends "base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
  {{ post.body|markdown }}
  <hr>
  <p>
    <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
  </p>
  <hr>
  <h2>Similar posts</h2>
  {% for post in similar_posts %}
    <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
  {% empty %}
    There are no similar posts
  {% endfor %}
  <hr>
  {% if new_comment %}
    <h2>Your comment has been successfully added.</h2>
  {% else %}
    <h2>Add a new comment</h2>
    <form method="post">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <p><input type="submit" value="Add Comment"></p>
    </form>
  {% endif %}
  {% with comments.count as total_comments %}
    <h3>{{ total_comments }} comment{{ total_comments|pluralize }}</h3>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>There are not comments yet.</p>
  {% endfor %}
{% endblock content %}

blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock title %}
{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    <p class="tags">
      Tags:
      {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.slug }}</a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends "base.html" %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock content %}

templates/base.html
{% load blog_tags %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
  </head>
  <body>
    <div id="content">
      {% block content %}
      {% endblock content %}
    </div>
    <div id="sidebar">
      <h2><a href="{% url 'blog:post_list' %}">My Blog</a></h2>
      <p>This is my blog. There are <strong>{% total_posts %}</strong> posts so far.</p>
      <p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>
      <hr>
      <h3>Latest Posts</h3>
      {% show_latest_posts 10 %}
      <hr>
      <h3>Most commented posts</h3>
      {% get_most_commented_posts 10 as most_commented_posts %}
      <ul>
        {% for post in most_commented_posts %}
          <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </body>
</html>

templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}

    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
  </span>
  {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
  {% endif %}
</div>